url: https://dariscalinor.github.io
baseurl: ""

# Site settings
title: Candogan Tuzcu
email: candogan.tuzcu@gmail.com
description: "Full Stack JavaScript Developer in Melbourne. Works with React.js, Node.js, Express.js and MongoDB."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/candovsky
  - title: linkedin
    url: https://linkedin.com/in/candogan-tuzcu
  - title: github
    url: https://github.com/DarisCalinor
    
# Postal address (add as many lines as necessary)
address:
  - line: Melbourne VIC 3000
  - line: Australia

# Build settings
markdown: kramdown
permalink: pretty